### ISSUE TITLE
[feature/hpc/ddr] MIG integration

### ISSUE THREAD

**Issue by MaistoV** [MaistoV/UninaSoC#16]
PR opened at https://github.com/MaistoV/UninaSoC/pull/25

Ingtegrate DDR MIG in HPC flow for Alveo U250.

> excluding CDC design from this item. For full CDC design refere to item https://github.com/users/MaistoV/projects/3/views/2?pane=issue&itemId=89678656

**Comment by DOTTORM5** [comment]
- For this task, the CDC is accomplished by simply using an AXI Clock Converter.
- For now, we use one DDR channel, the one nearest to the XDMA (PCIe), to be checked.
- For now, we can address only 4 GB of the 16 GB of the single DDR channel (we have just a 32-bit address).
